DROP TABLE IF EXISTS sms_type0_stage0;
DROP TABLE IF EXISTS sms_type0_stage1;
DROP TABLE IF EXISTS sms_type0_widths;
DROP TABLE IF EXISTS sms_type0_offsets;
DROP TABLE IF EXISTS conversation_type0_stage0;
DROP TABLE IF EXISTS conversation_type0_stage1;
DROP TABLE IF EXISTS conversation_type0_widths;
DROP TABLE IF EXISTS conversation_type0_offsets;

CREATE TABLE sms_type0_widths
  (
    record_offset INTEGER PRIMARY KEY NOT NULL,
    u0            SMALLINT,
    message_id    SMALLINT,
    u1            SMALLINT,
    thread_id     SMALLINT,
    u2            SMALLINT,
    FILETIME_0    SMALLINT,
    FILETIME_1    SMALLINT,
    direction     SMALLINT,
    FILETIME_2    SMALLINT,
    u3            SMALLINT,
    u4            SMALLINT,
    u5            SMALLINT,
    u6            SMALLINT,
    u7            SMALLINT,
    u8            SMALLINT,
    u9            SMALLINT,
    u10           SMALLINT,
    u11           SMALLINT,
    u11a          SMALLINT,
    phone_0       SMALLINT,
    SMStext       SMALLINT,
    content       SMALLINT,
    phone_1       SMALLINT,
    phone_2       SMALLINT,
    phone_3       SMALLINT,
    message       SMALLINT,
    FILETIME_2b   SMALLINT,
    u12           SMALLINT,
    FILETIME_3    SMALLINT,
    sim           SMALLINT,
    full_binary   SMALLINT
  );
CREATE TABLE sms_type0_offsets
  (
    record_offset INTEGER PRIMARY KEY NOT NULL,
    u0            SMALLINT,
    message_id    SMALLINT,
    u1            SMALLINT,
    thread_id     SMALLINT,
    u2            SMALLINT,
    FILETIME_0    SMALLINT,
    FILETIME_1    SMALLINT,
    direction     SMALLINT,
    FILETIME_2    SMALLINT,
    u3            SMALLINT,
    u4            SMALLINT,
    u5            SMALLINT,
    u6            SMALLINT,
    u7            SMALLINT,
    u8            SMALLINT,
    u9            SMALLINT,
    u10           SMALLINT,
    u11           SMALLINT,
    u11a          SMALLINT,
    phone_0       SMALLINT,
    SMStext       SMALLINT,
    content       SMALLINT,
    phone_1       SMALLINT,
    phone_2       SMALLINT,
    phone_3       SMALLINT,
    message       SMALLINT,
    FILETIME_2b   SMALLINT,
    u12           SMALLINT,
    FILETIME_3    SMALLINT,
    sim           SMALLINT,
    full_binary   SMALLINT
  );

CREATE TABLE sms_type0_stage0
  (
    record_offset BLOB,
    u0            BLOB,
    message_id    BLOB,
    u1            BLOB,
    thread_id     BLOB,
    u2            BLOB,
    FILETIME_0    BLOB,
    FILETIME_1    BLOB,
    direction     BLOB,
    FILETIME_2    BLOB,
    u3            BLOB,
    u4            BLOB,
    u5            BLOB,
    u6            BLOB,
    u7            BLOB,
    u8            BLOB,
    u9            BLOB,
    u10           BLOB,
    u11           BLOB,
    u11a          BLOB,
    phone_0       BLOB,
    SMStext       BLOB,
    content       BLOB,
    phone_1       BLOB,
    phone_2       BLOB,
    phone_3       BLOB,
    message       BLOB,
    FILETIME_2b   BLOB,
    u12           BLOB,
    FILETIME_3    BLOB,
    sim           BLOB,
    full_binary   BLOB
  );

CREATE TABLE sms_type0_stage1
  (
    record_offset INTEGER PRIMARY KEY NOT NULL,
    u0            BLOB,
    message_id    INTEGER,
    u1            BLOB,
    thread_id     INTEGER,
    u2            BLOB,
    FILETIME_0    INT8,
    FILETIME_1    INT8,
    direction     INTEGER,
    FILETIME_2    INT8,
    u3            BLOB,
    u4            BLOB,
    u5            BLOB,
    u6            BLOB,
    u7            BLOB,
    u8            BLOB,
    u9            BLOB,
    u10           BLOB,
    u11           BLOB,
    u11a          BLOB,
    phone_0       TEXT,
    SMStext       TEXT,
    content       TEXT,
    phone_1       TEXT,
    phone_2       TEXT,
    phone_3       TEXT,
    message       TEXT,
    FILETIME_2b   INT8,
    u12           BLOB,
    FILETIME_3    INT8,
    sim           TEXT,
    full_binary   BLOB
  );

CREATE TABLE conversation_type0_widths
  (
    record_offset   INT PRIMARY KEY NOT NULL,
    thread_id       SMALLINT,
    thread_length   SMALLINT,
    u0              SMALLINT,
    FILETIME_0      SMALLINT,
    u1              SMALLINT,
    phone_0         SMALLINT,
    phone_1         SMALLINT,
    phone_2         SMALLINT,
    FILETIME_1      SMALLINT,
    full_binary     SMALLINT
  );